pipeline:
  build:
    image: php:7.1.22
    volumes:
      - /usr/local/bin:/usr/local/bin
      - /mnt/data/drone/workspace:/drone/workspace
      - /mnt/data/drone/bin:/drone/bin
    commands:
      - . /drone/workspace/init
      - composer config -g repo.packagist composer https://packagist.laravel-china.org
      - composer update -o
    when:
      branch: [ master, develop ]
