INSERT INTO `menu` VALUES (1, '系统设置', NULL, '/systemSeting', 1, '{\"icon\":\"comp\", \"hidden\": false,\"title\":\"系统设置\"}');
INSERT INTO `menu` VALUES (2, '用户管理', 1, '/systemSeting/userManage/index', 2, '{\"title\":\"用户管理\"}');
INSERT INTO `menu` VALUES (3, '菜单管理', 1, '/systemSeting/menuManage/index', 3, '{\"title\":\"菜单管理\"}');
INSERT INTO `menu` VALUES (4, '权限管理', 1, '/systemSeting/permissionManage/index', 4, '{\"title\":\"权限管理\"}');
INSERT INTO `menu` VALUES (5, '角色管理', 1, '/systemSeting/roleManage/index', 5, '{\"title\":\"角色管理\"}');
INSERT INTO `menu` VALUES (6, '路由管理', 1, '/systemSeting/routeManage/index', 6, '{\"title\":\"路由管理\"}');
INSERT INTO `menu` VALUES (7, '规则管理', 1, '/systemSeting/ruleManage/index', 7, '{\"title\":\"规则管理\"}');
INSERT INTO `menu` VALUES (8, '操作日志', 1, '/systemSeting/logManage/index', 8, '{\"title\":\"操作日志\"}');
INSERT INTO `menu` VALUES (9, '商品管理', NULL, '/goodsManage', 9, '{\"icon\":\"widget\", \"hidden\": false,\"title\":\"商品管理\"}');
INSERT INTO `menu` VALUES (10, '商品列表', 9, '/goodsManage/index', 10, '{\"title\":\"商品列表\"}');
INSERT INTO `menu` VALUES (11, '订单管理', NULL, '/orderManage', 11, '{\"icon\":\"table\", \"hidden\": false,\"title\":\"订单管理\"}');
INSERT INTO `menu` VALUES (12, '订单列表', 11, '/orderManage/index', 12, '{\"title\":\"订单列表\"}');
