INSERT INTO `menu` VALUES (1, '系统设置', NULL, '', 1, '{\"icon\":\"el-icon-lx-settings\", \"visible\": false}');
INSERT INTO `menu` VALUES (2, '用户管理', 1, '/views/UM/userManage.vue', 2, NULL);
INSERT INTO `menu` VALUES (3, '菜单管理', 1, '/views/UM/menuManage.vue', 3, NULL);
INSERT INTO `menu` VALUES (4, '权限管理', 1, '/views/UM/permissionManage.vue', 4, NULL);
INSERT INTO `menu` VALUES (5, '角色管理', 1, '/views/UM/roleManage.vue', 5, NULL);
INSERT INTO `menu` VALUES (6, '路由管理', 1, '/views/UM/routeManage.vue', 6, NULL);
INSERT INTO `menu` VALUES (7, '规则管理', 1, '/views/UM/ruleManage.vue', 7, NULL);
INSERT INTO `menu` VALUES (8, '操作日志', 1, '/views/UM/logManage.vue', 8, NULL);
INSERT INTO `menu` VALUES (9, '商品管理', NULL, '', 9, '{\"icon\":\"el-icon-lx-cartfill\", \"visible\": false}');
INSERT INTO `menu` VALUES (10, '商品列表', 9, '/views/OSM/goodsManage.vue', 10, NULL);
INSERT INTO `menu` VALUES (11, '订单管理', NULL, NULL, 11, '{\"icon\":\"el-icon-lx-calendar\", \"visible\": false}');
INSERT INTO `menu` VALUES (12, '订单列表', 11, '/views/OSM/orderManage.vue', 12, NULL);
